from manim import *

class ComplexTrig(Scene):
    def construct(self):
        intro_text = Tex("We know the familiar $x$, $y$, and $r$:").move_to(2*UP)
        self.play(Write(intro_text))
        self.wait()
        self.play(Uncreate(intro_text))
        axes = Axes(x_range = [0, 5, 1], y_range = [0, 5, 1], axis_config={'include_ticks':False})
        self.play(Create(axes))
        point = Dot(axes.c2p(3,2))
        self.wait()
        self.play(Create(point))
        self.wait()
        point_lbl = Tex(r"$(x,y)$").next_to(point, RIGHT)
        self.play(Write(point_lbl))
        self.wait()
        hypotenuse = Line(axes.c2p(0,0), point, color=YELLOW)
        self.play(Create(hypotenuse))
        self.wait()
        horiz_brace = Brace(Line(axes.c2p(0,0), axes.c2p(3,0)), color=BLUE)
        horiz_txt = horiz_brace.get_text("$x$").set_color(BLUE)
        self.play(Create(horiz_brace))
        self.play(Write(horiz_txt))
        self.wait()
        vert_brace = BraceBetweenPoints(axes.c2p(3,0), axes.c2p(3,2)).set_color(RED)
        vert_txt = vert_brace.get_text("$y$").set_color(RED)
        self.play(Create(vert_brace))
        self.play(Write(vert_txt))
        self.wait()
        hypot_brace = BraceBetweenPoints(axes.c2p(3,2), axes.c2p(0,0)).set_color(YELLOW)
        hypot_txt = hypot_brace.get_text("$r$").set_color(YELLOW)
        self.play(Create(hypot_brace))
        self.play(Write(hypot_txt))
        self.wait()
        self.remove(axes, point, point_lbl, hypotenuse, horiz_brace, 
        horiz_txt, vert_brace, vert_txt, hypot_brace, hypot_txt)
        self.wait()

        complex_txt = Tex("With complex numbers, our plane becomes")
        self.play(Write(complex_txt))
        self.wait()
        self.play(Uncreate(complex_txt))
