from manim import *
import math

class Complex(Scene):
    def construct(self):
        plane = ComplexPlane().add_coordinates()
        self.play(Create(plane))
        dot1 = Dot(plane.c2p(2,3), color=YELLOW)
        lbl1 = Tex(r"$2+3i$").next_to(dot1, UR)
        dot2 = Dot(plane.c2p(-4,-1), color=GREEN)
        lbl2 = Tex(r"$-4-i$").next_to(dot2, UL)
        self.wait()
        point1 = VGroup(dot1, lbl1)
        self.play(Write(point1))
        self.wait()
        point2 = VGroup(dot2, lbl2)
        self.play(Write(point2))
        self.wait()

        vec1 = Line(plane.c2p(0,0), plane.c2p(2,3), color=YELLOW).add_tip()
        self.play(Create(vec1))
        self.wait()
        vec2 = Line(plane.c2p(0,0), plane.c2p(-4,-1), color=GREEN).add_tip()
        self.play(Create(vec2))
        self.wait()

        self.remove(point1, point2, plane, vec1, vec2)
        self.wait()

class AddVecs(Scene):
  def construct(self):
    title = Title("Adding and Subtracting Complex Numbers")
    self.play(Write(title))
    self.wait()

    intro_text1 = Tex(r"Adding and subtracting complex numbers works just like")
    intro_text2 = Tex(r"adding and subtracting expressions in algebra.").next_to(intro_text1, DOWN)
    intro_text = VGroup(intro_text1, intro_text2)
    self.play(Write(intro_text))
    self.wait()
    self.remove(title, intro_text)
    
    example = Tex(r"$(2+3i)$", r"$+$", r"$(-4-i)$").to_edge(UR, buff=1)
    answer = Tex(r"$-2 + 2i$").next_to(example, 1.5*DOWN)
    self.play(Write(example))
    self.wait()
    plane = ComplexPlane(x_range = [-5,5,1], y_range = [-5,5,1],
                         x_length = 8, y_length=8).add_coordinates().to_edge(LEFT)
    self.play(Create(plane))
    self.wait()

    real1 = example[0][1]
    real1_box = SurroundingRectangle(real1)
    real2 = example[2][1:3]
    real2_box = SurroundingRectangle(real2)
    self.play(Create(real1_box))
    self.play(Create(real2_box))
    self.wait()
    self.play(Write(answer[0][0:2]))
    self.wait()
    self.remove(real1_box, real2_box)
    self.wait()

    imag1 = example[0][3:5]
    imag1_box = SurroundingRectangle(imag1)
    imag2 = example[2][3:5]
    imag2_box = SurroundingRectangle(imag2)
    self.play(Create(imag1_box))
    self.play(Create(imag2_box))
    self.wait()
    self.play(Write(answer[0][2:]))
    self.wait()
    self.remove(imag1_box, imag2_box)
    self.wait()
    answer_box = SurroundingRectangle(answer, color=RED)
    self.play(Create(answer_box))
    self.wait()

    answer_dot = Dot(plane.c2p(-2,2), color=YELLOW)
    answer_vec = Line(start=plane.c2p(0,0), end=plane.c2p(-2,2), 
                      color=YELLOW).add_tip()
    self.play(Create(answer_dot))
    vec1 = Line(start=plane.c2p(0,0), end=plane.c2p(2,3)).add_tip()
    self.play(Create(vec1))
    self.wait()
    self.play(example[0][1:5].animate.move_to(plane.c2p(2,1.5)).scale(0.7))
    self.wait()
    vec2 = Line(start=plane.c2p(2,3), end=plane.c2p(-2,2),
                color=ORANGE).add_tip()
    self.play(Create(vec2))
    self.wait()
    self.play(example[2][1:5].animate.move_to(plane.c2p(-1,2.75)).scale(0.7))
    self.wait()
    self.play(Create(answer_vec))
    self.wait()
    self.play(answer.animate.move_to(plane.c2p(-2,1)).scale(0.7))
    self.wait()

    
class SubVecs(Scene):
  def construct(self):
    example = Tex(r"$(2+3i)$", r"$-$", r"$(-4-i)$").to_edge(UR, buff=1)
    answer = Tex(r"$6 + 4i$").next_to(example, 1.5*DOWN)
    self.play(Write(example))
    self.wait()
    plane = ComplexPlane(x_range = [0,7,1], y_range = [0,6,1],
                         x_length = 8, y_length=6).add_coordinates().to_edge(LEFT)
    self.play(Create(plane))
    self.wait()

    real1 = example[0][1]
    real1_box = SurroundingRectangle(real1)
    real2 = example[2][1:3]
    real2_box = SurroundingRectangle(real2)
    self.play(Create(real1_box))
    self.play(Create(real2_box))
    self.wait()
    self.play(Write(answer[0][0]))
    self.wait()
    self.remove(real1_box, real2_box)
    self.wait()

    imag1 = example[0][3:5]
    imag1_box = SurroundingRectangle(imag1)
    imag2 = example[2][3:5]
    imag2_box = SurroundingRectangle(imag2)
    self.play(Create(imag1_box))
    self.play(Create(imag2_box))
    self.wait()
    self.play(Write(answer[0][1:]))
    self.wait()
    self.remove(imag1_box, imag2_box)
    self.wait()
    answer_box = SurroundingRectangle(answer, color=RED)
    self.play(Create(answer_box))
    self.wait()

    answer_dot = Dot(plane.c2p(6,4), color=YELLOW)
    answer_vec = Line(start=plane.c2p(0,0), end=plane.c2p(6,4), 
                      color=YELLOW).add_tip()
    self.play(Create(answer_dot))
    vec1 = Line(start=plane.c2p(0,0), end=plane.c2p(2,3)).add_tip()
    self.play(Create(vec1))
    self.wait()
    self.play(example[0][1:5].animate.move_to(plane.c2p(0.75,2)).scale(0.7))
    self.wait()
    vec2 = Line(start=plane.c2p(2,3), end=plane.c2p(6,4),
                color=ORANGE).add_tip()
    self.play(Create(vec2))
    self.wait()
    self.play(example[1:3].animate.move_to(plane.c2p(3.5,3.75)).scale(0.7))
    self.wait()
    self.play(Create(answer_vec))
    self.wait()
    self.play(answer.animate.move_to(plane.c2p(4,2.25)).scale(0.7))
    self.wait()

class MultVecs(Scene):
  def construct(self):
    intro_text = Tex(r"Multiplying complex numbers is like multiplying expressions in algebra.").scale(0.8)
    self.play(Write(intro_text))
    self.wait()
    self.remove(intro_text)

    alg_example = Tex(r"\begin{align*}(4+3x)(2+x) &= 4(2) + 4(x) + 2(3x) + 3x(x) \\ &= 8 + 4x + 6x + 3x^2 \\ &= 3x^2 + 10x + 8\end{align*}").to_edge(UP, buff=1)
    self.play(Write(alg_example[0][:11]))  # (4+3x)(2+x)
    self.wait()
    self.play(Write(alg_example[0][11:33]))  # 4(2) + 4(x) + 3x(2) + 3x(x)
    self.wait()
    self.play(Write(alg_example[0][33:45]))  # 8 + 4x + 6x + 3x^2
    self.wait()
    self.play(Write(alg_example[0][45:]))  # 3x^2 + 10x + 8
    self.wait()
    self.play(Uncreate(alg_example))
    self.wait()

    example = Tex(r"$(4+3i)$", r"$(2+i)$").to_edge(UP, buff=1)
    self.play(Write(example))

    example1 = Tex(r"The only difference is we substitue $-1$")
    example2 = Tex(r"in for $i^2$ and then simplify.").next_to(example1, DOWN)
    additional_info = VGroup(example1, example2)
    self.play(Write(additional_info))
    self.wait()
    self.remove(additional_info)
    self.wait()

    complex_example = Tex(r"\begin{align*}(4+3i)(2+i) &= 4(2) + 4(i) + 3i(2) + 3i(i) \\ &= 8 + 4i + 6i + 3i^2 \\ &= 3i^2 + 10i + 8 \\ &= 3(-1) + 10i + 8 \\ &= -3 + 10i + 8 \\ &= 5 + 10i \end{align*}")
    self.play(Write(complex_example[0][:11]))  # (4+3i)(2+i)
    self.wait()
    self.play(Write(complex_example[0][11:33]))  # 4(2) + 4(i) + 2(3i) + 3i(i)
    self.wait()
    self.play(Write(complex_example[0][33:45]))  # 8 + 4i + 6i + 3i^2
    self.wait()
    self.play(Write(complex_example[0][45:55]))  # 3i^2 + 10i + 8
    self.wait()
    i2_box = SurroundingRectangle(complex_example[0][47:49])  # highlight i^2
    self.play(Create(i2_box))
    self.wait()
    self.play(Write(complex_example[0][55:67]))  # 3(-1) + 10i + 8
    self.wait()
    self.remove(i2_box)
    self.play(Write(complex_example[0][67:76]))  # -3 + 10i + 8
    self.wait()
    self.play(Write(complex_example[0][76:]))  # 5 + 10i
    self.wait()
    self.play(Uncreate(example))
    self.play(Uncreate(complex_example))
    self.wait()

    plane = ComplexPlane(x_range = [0,11,1], y_range = [0,11,1],
                         x_length = 8, y_length=8).add_coordinates().to_edge(LEFT, buff=0.2).scale(0.95)
    self.play(Create(plane))
    self.wait()
    example = Tex(r"$4+3i$", r"$2+i$")
    complex_num1 = example[0].to_edge(UR, buff=1).set_color(YELLOW)
    self.play(Write(complex_num1))
    vec1 = Line(start=plane.c2p(0,0), end=plane.c2p(4,3), color=YELLOW).add_tip()
    self.wait()
    dot1 = Dot(plane.c2p(4,3), color=YELLOW)
    self.play(Create(dot1))
    self.wait()
    self.play(Create(vec1))
    self.wait()
    complex_num2 = example[1].next_to(complex_num1, DOWN).set_color(BLUE)
    self.play(Write(complex_num2))
    self.wait()
    vec2 = Line(start=plane.c2p(0,0), end=plane.c2p(2,1), color=BLUE).add_tip()
    self.wait()
    dot2 = Dot(plane.c2p(2,1), color=BLUE)
    self.play(Create(dot2))
    self.wait()
    self.play(Create(vec2))
    self.wait()
    answer = Tex(r"$5 + 10i$").next_to(complex_num2, DOWN).set_color(RED)
    answer_dot = Dot(plane.c2p(5,10), color=RED)
    self.play(Write(answer))
    self.play(Create(answer_dot))
    self.wait()
    answer_vec = Line(start=plane.c2p(0,0), end=plane.c2p(5,10), color=RED).add_tip()
    self.play(Create(answer_vec))
    self.wait()

    self.remove(vec2, answer_vec)
    self.wait()

    brace1 = BraceBetweenPoints(plane.c2p(4,3), plane.c2p(0,0), color=YELLOW)
    self.play(Create(brace1))
    self.wait()
    vec1_mag = brace1.get_text("5", buff=0.1).set_color(YELLOW)
    self.play(Write(vec1_mag))
    self.remove(complex_num1)
    self.wait()
    vec1_mag_text = Tex(r"Length of vector 1 is 5", color=YELLOW).to_edge(UR, buff=0.2)
    self.play(Write(vec1_mag_text))
    self.wait()
    self.remove(vec1, brace1, vec1_mag)
    self.wait()

    self.play(Create(vec2))
    self.wait()
    brace2 = BraceBetweenPoints(plane.c2p(2,1), plane.c2p(0,0), color=BLUE)
    self.play(Create(brace2))
    self.wait()
    vec2_mag = brace2.get_text("2.24", buff=0.1).set_color(BLUE)
    self.play(Write(vec2_mag))
    self.remove(complex_num2)
    self.wait()
    vec2_mag_text = Tex(r"Length of vector 2 is 2.24", color=BLUE).next_to(vec1_mag_text, DOWN, buff=0.1).scale(0.95)
    self.play(Write(vec2_mag_text))
    self.wait()
    self.remove(vec2, brace2, vec2_mag)
    self.wait()

    self.play(Create(answer_vec))
    self.wait()
    answer_brace = BraceBetweenPoints(plane.c2p(5,10), plane.c2p(0,0), color=RED)
    self.play(Create(answer_brace))
    self.wait()
    answer_mag = answer_brace.get_text("11.2", buff=0.1).set_color(RED)
    self.play(Write(answer_mag))
    self.remove(answer)
    self.wait()
    answer_mag_text = Tex(r"Length of vector 3 is 11.2", color=RED).next_to(vec2_mag_text, DOWN, buff=0.1).scale(0.95)
    self.play(Write(answer_mag_text))
    self.wait()

    self.remove(dot1, dot2, answer_dot, answer_vec, answer_brace, answer_mag)
    self.wait()

    self.play(Write(vec1))
    self.wait()

    x_axis = Line(plane.c2p(0,0), plane.c2p(5,0))
    vec1_angle = Angle(x_axis, vec1, radius=1.5)
    self.play(Create(vec1_angle))
    value = DecimalNumber(vec1_angle.get_value(degrees=True), unit="^{\circ}", color=YELLOW)
    self.play(Write(value.next_to(vec1_angle, RIGHT ,buff=0.5)))
    self.wait()
    self.play(Write(value.next_to(answer_mag_text, DOWN)))
    self.play(Uncreate(vec1_angle))
    self.play(Uncreate(vec1))
    self.wait()

    self.play(Create(vec2))
    self.wait()
    vec2_angle = Angle(x_axis, vec2, radius=1.5)
    self.play(Create(vec2_angle))
    value2 = DecimalNumber(vec2_angle.get_value(degrees=True), unit="^{\circ}", color=BLUE)
    self.play(Write(value2.next_to(vec2_angle, RIGHT ,buff=0.25)))
    self.wait()
    self.play(Write(value2.next_to(value, DOWN)))
    self.play(Uncreate(vec2))
    self.play(Uncreate(vec2_angle))
    self.wait()

    self.play(Create(answer_vec))
    self.wait()
    answer_vec_angle = Angle(x_axis, answer_vec, radius=1.5)
    self.play(Create(answer_vec_angle))
    value3 = DecimalNumber(answer_vec_angle.get_value(degrees=True), unit="^{\circ}", color=RED)
    self.play(Write(value3.next_to(answer_vec_angle, RIGHT ,buff=0.25)))
    self.wait()
    self.play(Write(value3.next_to(value2, DOWN)))
    self.play(Uncreate(answer_vec))
    self.play(Uncreate(answer_vec_angle))
    self.wait(2)

    self.remove(vec1_mag_text, vec2_mag_text, answer_mag_text, plane, 
                value, value2, value3)
    self.wait()

    revelation = Tex("When multiplying complex numbers, \n"
                    "we multiply the lengths of the vectors \n"
                    "and add the angles they make with the positive $x$-axis.").scale(0.8)
    self.play(Write(revelation))
    self.wait()

class Conjugate(Scene):
  def construct(self):
    example = Tex(r"$(2+i)(2-i)$").to_edge(UP, buff=0.5)
    self.play(Write(example))
    self.wait()

    plane = ComplexPlane(x_range = [-2,6,1], y_range=[-3,3,1]).add_coordinates().to_edge(DL, buff=0.5)
    xaxis = Line(start=plane.c2p(0,0), end=plane.c2p(5,0))
    self.play(Create(plane))
    self.wait()
    box1 = SurroundingRectangle(example[0][1:4])
    self.play(Create(box1))
    self.wait()
    vec1 = Line(start=plane.c2p(0,0), end=plane.c2p(2,1), color=YELLOW).add_tip()
    self.play(Create(vec1))
    self.wait()
    vec1_brace = BraceBetweenPoints(plane.c2p(2,1), plane.c2p(0,0), color=YELLOW)
    vec1_mag = vec1_brace.get_text(r"$\sqrt{5}$", buff=0.1).set_color(YELLOW)
    self.play(Create(vec1_brace))
    self.play(Write(vec1_mag))
    self.wait()
    angle1 = Angle(xaxis, vec1, color=YELLOW)
    angle1_measure = DecimalNumber(angle1.get_value(degrees=True), unit="^{\circ}", color=YELLOW).scale(0.8)
    self.play(Write(angle1_measure.next_to(angle1, 2*RIGHT + 0.15*UP)))
    self.wait()
    vec1_grp = VGroup(box1, vec1, vec1_brace, vec1_mag, angle1_measure)
    mag_and_angle = Tex(r"$\sqrt{5} \quad 26.57^\circ$").set_color(YELLOW).to_edge(RIGHT + 1.25*UP, buff=0.2)
    self.play(Write(mag_and_angle))
    self.play(Uncreate(vec1_grp))
    self.wait()
    box2 = SurroundingRectangle(example[0][6:9], color=BLUE)
    self.play(Create(box2))
    self.wait()
    vec2 = Line(start=plane.c2p(0,0), end=plane.c2p(2,-1), color=BLUE).add_tip()
    self.play(Create(vec2))
    self.wait()
    vec2_brace = BraceBetweenPoints(plane.c2p(2,-1), plane.c2p(0,0), color=BLUE)
    vec2_mag = vec2_brace.get_text(r"$\sqrt{5}$", buff=0.1).set_color(BLUE)
    self.play(Create(vec2_brace))
    self.play(Write(vec2_mag))
    self.wait()
    angle2 = Angle(xaxis, vec2, color=BLUE)
    self.play(Create(angle2))
    angle2_measure = DecimalNumber(angle2.get_value(degrees=True), unit="^{\circ}", color=BLUE).scale(0.8)
    self.play(Write(angle2_measure.next_to(angle2, UL, buff=0.1)))
    self.wait()
    vec2_grp = VGroup(box2, vec2, vec2_brace, vec2_mag, angle2, angle2_measure)
    mag_and_angle2 = Tex(r"$\sqrt{5} \quad 333.43^\circ$").set_color(BLUE).next_to(mag_and_angle, DOWN)
    self.play(Write(mag_and_angle2))
    self.play(Uncreate(vec2_grp))
    self.wait()

    vec3 = Line(start=plane.c2p(0,0), end=plane.c2p(5,0), color=RED).add_tip()
    vec3_mag_and_angle = Tex(r"$5 \quad 360^\circ$").set_color(RED).next_to(mag_and_angle2, DOWN)
    self.play(Write(vec3_mag_and_angle))
    self.wait()
    self.play(Create(vec3))
    self.wait()

class DivideComplex(Scene):
  def construct(self):
    example1 = Text("Example. Divide the following.", t2c = {'Example.': RED}).to_edge(UP)
    problem1 = Tex(r"$\dfrac{3+2i}{5}$").next_to(example1, DOWN)
    self.play(Write(example1))
    self.play(Write(problem1))
    self.wait()
    answer1 = Tex(r"$\dfrac{3}{5} + \dfrac{2}{5}i$").next_to(problem1, 1.5*DOWN)
    self.play(Write(answer1))
    box1 = SurroundingRectangle(answer1)
    self.play(Create(box1))
    self.wait()
    example1_grp = VGroup(example1, problem1, answer1, box1)
    self.play(Uncreate(example1_grp))
    self.wait()

    txt_complex_denom = Text("But what if the denominator is a complex number?")
    self.play(Write(txt_complex_denom))
    self.wait()
    problem2 = Tex(r"$\dfrac{3-i}{2+i}$").next_to(txt_complex_denom, DOWN)
    self.play(Write(problem2))
    self.wait()
    self.play(Uncreate(txt_complex_denom))
    self.play(problem2.animate.to_edge(UP))
    self.wait()
    conjug_txt = Text("We can get a real value for the denominator \n "
                      "if we multiply it by its conjugate.", t2c = {'conjugate.': YELLOW})
    self.play(Write(conjug_txt))
    self.wait()
    self.play(Uncreate(conjug_txt))
    self.wait()
    self.play(problem2.animate.to_edge(UL))
    self.wait()
    problem2_step1 = Tex(r"$\dfrac{(2-i)}{(2-i)}$").next_to(problem2, RIGHT)
    self.play(Write(problem2_step1))
    self.wait()
    problem2_step2 = Tex(r"$=\dfrac{(3-i)(2-i)}{(2+i)(2-i)}$").next_to(problem2_step1, RIGHT)
    self.play(Write(problem2_step2))
    self.wait()
    problem2_step3 = Tex(r"$=\dfrac{3(2)-3(i)-i(2)-i(-i)}{5}$").next_to(problem2_step2, 1.5*DOWN)
    self.play(Write(problem2_step3))
    self.wait()
    problem2_step4 = Tex(r"$=\dfrac{6-3i-2i+i^2}{5}$").next_to(problem2_step3, DOWN)
    self.play(Write(problem2_step4))
    self.wait()
    problem2_step5 = Tex(r"$=\dfrac{6-3i-2i-1}{5}$").next_to(problem2_step4, DOWN)
    self.play(Write(problem2_step5))
    self.wait()
    problem2_step6 = Tex(r"$=\dfrac{5-5i}{5}$").next_to(problem2_step5, DOWN)
    self.play(Write(problem2_step6))
    self.wait()
    problem2_step7 = Tex(r"$=\dfrac{5}{5} - \dfrac{5}{5}i$").next_to(problem2_step6, RIGHT)
    self.play(Write(problem2_step7))
    self.wait()
    answer2 = Tex(r"$=1-i$").next_to(problem2_step7, RIGHT)
    self.play(Write(answer2))
    self.wait()
    answer2_box = SurroundingRectangle(answer2[0][1:])
    self.play(Create(answer2_box))
    self.wait()
    problem2_grp = VGroup(problem2, problem2_step1, problem2_step2, problem2_step3,
                    problem2_step4, problem2_step5, problem2_step6, problem2_step7,
                    answer2, answer2_box)
    self.play(Uncreate(problem2_grp))
    self.wait()

    plane = ComplexPlane(x_range = [-2,4,1], y_range=[-2,4,1]).add_coordinates().to_edge(LEFT, buff=0.2)
    self.play(Create(plane))
    self.wait()
    problem2_complete = Tex(r"$\dfrac{3-i}{2+i} = 1-i$").to_edge(UR)
    self.play(Create(problem2_complete))
    self.wait()
    numer_box = SurroundingRectangle(problem2_complete[0][:3])
    self.play(Create(numer_box))
    self.wait()
    numer_vec = Line(start=plane.c2p(0,0), end=plane.c2p(3,-1), color=YELLOW).add_tip()
    self.play(Create(numer_vec))
    self.wait()
    xaxis = Line(start = plane.c2p(0,0), end = plane.c2p(4,0))
    numer_angle = Angle(xaxis, numer_vec, color=YELLOW)
    self.play(Create(numer_angle))
    numer_angle_measure = Integer(numer_angle.get_value(degrees=True), unit="^{\circ}", color=YELLOW).next_to(numer_angle, UL)
    self.play(Write(numer_angle_measure))
    self.wait()
    numer_brace = BraceBetweenPoints(plane.c2p(3,-1), plane.c2p(0,0), color=YELLOW)
    self.play(Create(numer_brace))
    self.wait()
    numer_mag = numer_brace.get_text(r"$\sqrt{10}$").set_color(YELLOW)
    self.play(Write(numer_mag))
    self.wait()
    numer_mag_and_angle = Tex(r"$\sqrt{10} \quad 342^\circ$").set_color(YELLOW).next_to(problem2_complete, 1.5*DOWN)
    self.play(Write(numer_mag_and_angle))
    self.wait()
    numer_grp = VGroup(numer_box, numer_vec, numer_angle, numer_angle_measure, 
                      numer_brace, numer_mag, numer_mag_and_angle)
    self.play(Uncreate(numer_grp))
    self.wait()
    denom_box = SurroundingRectangle(problem2_complete[0][4:7], color=ORANGE)
    self.play(Create(denom_box))
    self.wait()
    denom_vec = Line(start = plane.c2p(0,0), end=plane.c2p(2,1), color=ORANGE).add_tip()
    self.play(Create(denom_vec))
    self.wait()
    denom_angle = Angle(xaxis, denom_vec, color = ORANGE)
    self.play(Create(denom_angle))
    self.wait()